### ISSUE TITLE
Update schools models

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz_example_data#7]
The code in https://github.com/arviz-devs/arviz_example_data/blob/main/code/non_centered_eight/non_centered_eight.ipynb shows the generated inferencedata has the log_likelihood group, but the nc does not. Both centered and non-centered should be updated to match this.

I am not sure how this will propagate towards python and julia packages @sethaxen is updating this file alone enough? Is there any metadata also that should be updated?

**Comment by sethaxen** [comment]
Since they're stored in this repo, it's sufficient here to 1) update the netCDF file and 2) tag a new version.

The individual packages are then updated to use this as follows:
- python: https://python.arviz.org/en/latest/contributing/updating_example_data.html
- julia: http://exampledata.julia.arviz.org/stable/for_developers/
